import createShot from "@/assets/screenshots/create.png";
import homeShot from "@/assets/screenshots/home.png";
import playShot from "@/assets/screenshots/play.png";

const SHOTS = [
  {
    image: createShot,
    title: "Design Your Podcaster",
    description:
      "Build a virtual podcaster from scratch. Name, voice, personality, intellectual angle. Every host is yours.",
  },
  {
    image: homeShot,
    title: "Discover & Listen",
    description:
      "Browse a feed of episodes generated by the community across every genre. Pick up where you left off.",
  },
  {
    image: playShot,
    title: "Live Transcripts",
    description:
      "Follow along with synced transcripts as your Virtual Podcaster breaks down the book. Skip, rewind, or just listen.",
  },
];

export function Screenshots() {
  return (
    <section id="screenshots" className="py-20 md:py-28 bg-[#FBF8F2]">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="font-['DM_Serif_Display',serif] text-[#2f2f2f] text-4xl md:text-5xl mb-4">
            Inside the App
          </h2>
          <p className="font-['Plus_Jakarta_Sans',sans-serif] text-[#5a5a5a] text-lg md:text-xl max-w-2xl mx-auto">
            A look at how creators design, discover, and listen on Auditure.
          </p>
        </div>

        <div className="grid gap-12 md:grid-cols-3 items-start">
          {SHOTS.map((shot, idx) => (
            <div key={shot.title} className="text-center">
              <div className="relative mb-6 flex justify-center">
                <img
                  src={shot.image}
                  alt={shot.title}
                  className="w-full max-w-[280px] h-auto drop-shadow-2xl"
                  loading={idx === 0 ? "eager" : "lazy"}
                />
              </div>
              <h3 className="font-['DM_Serif_Display',serif] text-[#2f2f2f] text-2xl mb-3">
                {shot.title}
              </h3>
              <p className="font-['Plus_Jakarta_Sans',sans-serif] text-[#5a5a5a] leading-relaxed max-w-sm mx-auto">
                {shot.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
