import { Reveal } from "./reveal";
import createShot from "@/assets/screenshots/create.png";
import homeShot from "@/assets/screenshots/home.png";
import playShot from "@/assets/screenshots/play.png";

/*
 * Chapter III. Plates, the way an illustrated book carries them: each screen is
 * a full-bleed panel that alternates side, with its caption set small in the
 * facing margin. Replaces the three-up centred grid, which was the most
 * template-shaped thing left on the page.
 */
/*
 * home.png ships 921x1700 carrying 126px of export junk on the right: a stray
 * cream rectangle and a red sliver floating outside the phone bezel.
 *
 * Measured rather than eyeballed. Column opacity across home.png shows the
 * phone body ending at x=792 with its antialiased edge at x=794, then a flat
 * 3.6% residue out to x=920 which is the junk. create.png holds the identical
 * phone (body also ends x=792) and is exactly 795 wide, so 795 is the phone's
 * true width and the correct crop.
 *
 * `usableWidth` scales the image inside a clipping wrapper so only the phone
 * shows. Re-export the asset at 795px wide and this can go.
 */
const PLATES = [
  {
    image: createShot,
    plate: "Plate I",
    title: "Design Your Podcaster",
    description:
      "Build a virtual podcaster from scratch. Name, voice, personality, intellectual angle. Every host is yours.",
    usableWidth: 1,
  },
  {
    image: homeShot,
    plate: "Plate II",
    title: "Discover & Listen",
    description:
      "Browse a feed of episodes generated by the community across every genre. Pick up where you left off.",
    usableWidth: 795 / 921,
  },
  {
    image: playShot,
    plate: "Plate III",
    title: "Live Transcripts",
    description:
      "Follow along with synced transcripts as your Virtual Podcaster breaks down the book. Skip, rewind, or just listen.",
    usableWidth: 1,
  },
];

export function Screenshots() {
  return (
    <section id="screenshots" className="py-20 md:py-28 bg-[#1A1512] overflow-hidden">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        {/* Folio line, consistent across chapters */}
        <div className="border-t border-[#EDE4D6]/25 pt-3 flex items-baseline justify-between gap-4">
          <span className="label-caps text-[#EDE4D6]/50">III</span>
          <span className="label-caps text-[#EDE4D6]/50">Inside the App</span>
        </div>
      </div>

      <div className="mt-14 md:mt-20">
        {PLATES.map((plate, i) => {
          const flipped = i % 2 === 1;
          return (
            /*
             * Full-width two-column grid. The image cell simply runs to the
             * viewport edge on its own side, which is a true bleed. Earlier this
             * used negative margins on an unconstrained row, which overflowed and
             * left artefacts once the plate flipped sides.
             */
            <Reveal key={plate.plate} className="grid md:grid-cols-2 md:items-center">
              <div
                className={`bg-[#221A16] flex justify-center px-8 py-14 md:px-12 md:py-20 ${
                  flipped ? 'md:order-2' : ''
                }`}
              >
                <div className="w-full max-w-[260px] overflow-hidden">
                  <img
                    src={plate.image}
                    alt={plate.title}
                    className="h-auto max-w-none"
                    style={{ width: `${100 / plate.usableWidth}%` }}
                    loading={i === 0 ? 'eager' : 'lazy'}
                  />
                </div>
              </div>

              {/* Caption sits in the facing margin */}
              <div
                className={`px-4 sm:px-6 lg:px-12 py-12 md:py-0 ${
                  flipped ? 'md:order-1 md:flex md:justify-end' : ''
                }`}
              >
                <div className="md:max-w-[24em]">
                  <p className="label-caps text-[#C2A14D]/70 mb-5">{plate.plate}</p>
                  <h3 className="font-['EB_Garamond',serif] text-[#EDE4D6] display-tight text-3xl md:text-4xl">
                    {plate.title}
                  </h3>
                  <p className="font-['EB_Garamond',serif] text-[#A2907C] text-lg leading-relaxed mt-4">
                    {plate.description}
                  </p>
                </div>
              </div>
            </Reveal>
          );
        })}
      </div>
    </section>
  );
}
